platform :ios, '13.0'
use_frameworks!

target 'Bitski_Example' do
  supports_swift_versions '>= 5.0'
  pod 'Bitski', :path => '../'
  pod 'Web3', '0.3.1'
end

target 'Bitski_Tests' do
  supports_swift_versions '>= 5.0'
  pod 'Bitski', :path => '../'
  pod 'Web3', '0.3.1'
  pod 'OHHTTPStubs/Swift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Web3'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
