platform :ios, '11.0'
use_frameworks!

target 'Bitski_Example' do
  pod 'Bitski', :path => '../'
  pod 'Web3'
  pod 'Web3/PromiseKit'
  pod 'BigInt.swift'
  pod 'AppAuth'
  pod 'PromiseKit/CorePromise'
end

target 'Bitski_Tests' do
    pod 'Bitski', :path => '../'
    pod 'Web3'
    pod 'Web3/PromiseKit'
    pod 'BigInt.swift'
    pod 'AppAuth'
    pod 'PromiseKit/CorePromise'
end

target 'ABITests' do
    pod 'Bitski', :path => '../'
    pod 'Web3'
    pod 'Web3/PromiseKit'
    pod 'BigInt.swift'
    pod 'PromiseKit/CorePromise'
end

target 'ContractTests' do
    pod 'Bitski', :path => '../'
    pod 'Web3'
    pod 'Web3/PromiseKit'
    pod 'BigInt.swift'
    pod 'PromiseKit/CorePromise'
end
