platform :ios, '12.0'
use_frameworks!

target 'Bitski_Example' do
  supports_swift_versions '>= 5.0'
  pod 'Bitski', :path => '../'
  pod 'Web3', '0.4.2'
end

target 'Bitski_Tests' do
    supports_swift_versions '>= 5.0'
    pod 'Bitski', :path => '../'
    pod 'Web3', '0.4.2'
    pod 'OHHTTPStubs/Swift'
end
